[build]
command = "npm run build"
publish = ".next"  # Changed from "out" because you're using dynamic routes (App Router)

[functions]
directory = "netlify/functions"

[plugins]
  package = "@netlify/plugin-nextjs"
